/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.AppointmentDAO;
import dao.PatientDAO;
import dao.DentistDAO;
import dao.TreatmentDAO;

import model.Appointment;
import model.Patient;
import model.Dentist;
import model.Treatment;

import java.sql.Date;
import java.sql.Time;
import javax.swing.JOptionPane;

import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dinuli Disara
 */
public class AppointmentManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppointmentManagementForm.class.getName());
private final AppointmentDAO appointmentDAO = new AppointmentDAO();
    private final PatientDAO patientDAO = new PatientDAO();
private final DentistDAO dentistDAO = new DentistDAO();
private final TreatmentDAO treatmentDAO = new TreatmentDAO();
    /**
     * Creates new form AppointmentManagementForm
     */
    public AppointmentManagementForm() {
        initComponents();
         txtAppointmentId.setEditable(false);
    txtCreatedBy.setEditable(false);

    loadPatients();
    loadDentists();
    loadTreatments();
    loadAppointments();
    }
    private void loadPatients() {

    cmbPatient.removeAllItems();
    cmbPatient.addItem("Select Patient");

    List<Patient> patients = patientDAO.getAllPatients();

    for (Patient patient : patients) {
        cmbPatient.addItem(
                patient.getPatientId() + " - " + patient.getName()
        );
    }
}
private void loadDentists() {

    cmbDentist.removeAllItems();
    cmbDentist.addItem("Select Dentist");

    List<Dentist> dentists = dentistDAO.getActiveDentists();

    for (Dentist dentist : dentists) {
        cmbDentist.addItem(
                dentist.getDentistId() + " - " + dentist.getName()
        );
    }
}
private void loadTreatments() {

    cmbTreatment.removeAllItems();
    cmbTreatment.addItem("Select Treatment");

    List<Treatment> treatments = treatmentDAO.getAllTreatments();

    for (Treatment treatment : treatments) {

        if ("ACTIVE".equalsIgnoreCase(treatment.getStatus())) {

            cmbTreatment.addItem(
                    treatment.getTreatmentId()
                    + " - "
                    + treatment.getTreatmentName()
            );
        }
    }
}
private void loadAppointments() {

    DefaultTableModel model =
            (DefaultTableModel) tblAppointments.getModel();

    model.setRowCount(0);

    List<Appointment> appointments =
            appointmentDAO.getAllAppointments();

    for (Appointment appointment : appointments) {

        String patientName = "";
        String dentistName = "";
        String treatmentName = "";

        Patient patient =
                patientDAO.findById(appointment.getPatientId());

        if (patient != null) {
            patientName = patient.getName();
        }

        Dentist dentist =
                dentistDAO.findById(appointment.getDentistId());

        if (dentist != null) {
            dentistName = dentist.getName();
        }

        Treatment treatment =
                treatmentDAO.findById(appointment.getTreatmentId());

        if (treatment != null) {
            treatmentName = treatment.getTreatmentName();
        }

        model.addRow(new Object[]{
            appointment.getAppointmentId(),
            appointment.getAppointmentNo(),
            patientName,
            dentistName,
            treatmentName,
            appointment.getAppointmentDate(),
            appointment.getAppointmentTime(),
            appointment.getStatus(),
            appointment.getCreatedBy()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAppointmentId = new javax.swing.JTextField();
        txtAppointmentNo = new javax.swing.JTextField();
        cmbPatient = new javax.swing.JComboBox<>();
        cmbDentist = new javax.swing.JComboBox<>();
        cmbTreatment = new javax.swing.JComboBox<>();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtCreatedBy = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APPOINMENT MANAGEMENT");

        jLabel2.setText("Appointment ID");

        jLabel3.setText("Appointment No");

        jLabel4.setText("Patient");

        jLabel5.setText("Dentist");

        jLabel6.setText("Treatment");

        jLabel7.setText("Appointment Date");

        jLabel8.setText("Appointment Time");

        jLabel9.setText("Status");

        jLabel10.setText("Created By");

        txtAppointmentId.setEditable(false);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW" }));

        txtCreatedBy.setEditable(false);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Appointment No", "Patient", "Dentist", "Treatment", "Date", "Time", "Status", "Created By"
            }
        ));
        tblAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAppointmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAppointments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCreatedBy)
                                    .addComponent(cmbStatus, 0, 344, Short.MAX_VALUE)
                                    .addComponent(txtAppointmentTime)
                                    .addComponent(cmbTreatment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbDentist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAppointmentNo)
                                    .addComponent(txtAppointmentId)
                                    .addComponent(txtAppointmentDate))))))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAppointmentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAppointmentsMouseClicked
 int selectedRow = tblAppointments.getSelectedRow();

    if (selectedRow < 0) {
        return;
    }

    // Appointment ID
    txtAppointmentId.setText(
            tblAppointments.getValueAt(selectedRow, 0).toString()
    );

    // Appointment Number
    txtAppointmentNo.setText(
            tblAppointments.getValueAt(selectedRow, 1).toString()
    );

    // Patient
    String patientName =
            tblAppointments.getValueAt(selectedRow, 2).toString();

    selectComboByName(cmbPatient, patientName);

    // Dentist
    String dentistName =
            tblAppointments.getValueAt(selectedRow, 3).toString();

    selectComboByName(cmbDentist, dentistName);

    // Treatment
    String treatmentName =
            tblAppointments.getValueAt(selectedRow, 4).toString();

    selectComboByName(cmbTreatment, treatmentName);

    // Date
    Object date =
            tblAppointments.getValueAt(selectedRow, 5);

    txtAppointmentDate.setText(
            date != null ? date.toString() : ""
    );

    // Time
    Object time =
            tblAppointments.getValueAt(selectedRow, 6);

    txtAppointmentTime.setText(
            time != null ? time.toString() : ""
    );

    // Status
    Object status =
            tblAppointments.getValueAt(selectedRow, 7);

    if (status != null) {
        cmbStatus.setSelectedItem(status.toString());
    }

    // Created By
    Object createdBy =
            tblAppointments.getValueAt(selectedRow, 8);

    txtCreatedBy.setText(
            createdBy != null ? createdBy.toString() : ""
    );        // TODO add your handling code here:
    }//GEN-LAST:event_tblAppointmentsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
   String appointmentNo = txtAppointmentNo.getText().trim();
    String patientItem = cmbPatient.getSelectedItem().toString();
    String dentistItem = cmbDentist.getSelectedItem().toString();
    String treatmentItem = cmbTreatment.getSelectedItem().toString();
    String dateText = txtAppointmentDate.getText().trim();
    String timeText = txtAppointmentTime.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();
    String createdByText = txtCreatedBy.getText().trim();

    // Basic validation
    if (appointmentNo.isEmpty()
            || dateText.isEmpty()
            || timeText.isEmpty()
            || createdByText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (cmbPatient.getSelectedIndex() == 0
            || cmbDentist.getSelectedIndex() == 0
            || cmbTreatment.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select Patient, Dentist and Treatment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {

        // Get IDs from combo boxes
        int patientId = Integer.parseInt(
                patientItem.split(" - ")[0]
        );

        int dentistId = Integer.parseInt(
                dentistItem.split(" - ")[0]
        );

        int treatmentId = Integer.parseInt(
                treatmentItem.split(" - ")[0]
        );

        // Convert date
        Date appointmentDate = Date.valueOf(dateText);

        // Convert time
        Time appointmentTime = Time.valueOf(timeText);

        // Created By
        int createdBy = Integer.parseInt(createdByText);

        Appointment appointment = new Appointment(
                0,
                appointmentNo,
                patientId,
                dentistId,
                treatmentId,
                appointmentDate,
                appointmentTime,
                status,
                createdBy
        );

        boolean result =
                appointmentDAO.insertAppointment(appointment);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment added successfully."
            );

            loadAppointments();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to add appointment.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid ID value.",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
    );

} catch (IllegalArgumentException e) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid date or time.\n\n"
            + "Date format: YYYY-MM-DD\n"
            + "Time format: HH:MM:SS",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
    );
} // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
  if (txtAppointmentId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String appointmentNo = txtAppointmentNo.getText().trim();
    String patientItem = cmbPatient.getSelectedItem().toString();
    String dentistItem = cmbDentist.getSelectedItem().toString();
    String treatmentItem = cmbTreatment.getSelectedItem().toString();
    String dateText = txtAppointmentDate.getText().trim();
    String timeText = txtAppointmentTime.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();
    String createdByText = txtCreatedBy.getText().trim();

    if (appointmentNo.isEmpty()
            || dateText.isEmpty()
            || timeText.isEmpty()
            || createdByText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (cmbPatient.getSelectedIndex() == 0
            || cmbDentist.getSelectedIndex() == 0
            || cmbTreatment.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select Patient, Dentist and Treatment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {

        int appointmentId =
                Integer.parseInt(txtAppointmentId.getText().trim());

        int patientId =
                Integer.parseInt(patientItem.split(" - ")[0]);

        int dentistId =
                Integer.parseInt(dentistItem.split(" - ")[0]);

        int treatmentId =
                Integer.parseInt(treatmentItem.split(" - ")[0]);

        int createdBy =
                Integer.parseInt(createdByText);

        Date appointmentDate =
                Date.valueOf(dateText);

        Time appointmentTime =
                Time.valueOf(timeText);

        Appointment appointment = new Appointment(
                appointmentId,
                appointmentNo,
                patientId,
                dentistId,
                treatmentId,
                appointmentDate,
                appointmentTime,
                status,
                createdBy
        );

        boolean result =
                appointmentDAO.updateAppointment(appointment);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment updated successfully."
            );

            loadAppointments();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update appointment.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid ID value.",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
    );

} catch (IllegalArgumentException e) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid date or time.\n\n"
            + "Date format: YYYY-MM-DD\n"
            + "Time format: HH:MM:SS",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
    );
}       // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
  if (txtAppointmentId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int appointmentId;

    try {
        appointmentId = Integer.parseInt(
                txtAppointmentId.getText().trim()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid appointment ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this appointment?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean result =
            appointmentDAO.deleteAppointment(appointmentId);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Appointment deleted successfully."
        );

        loadAppointments();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to delete appointment.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed
private void selectComboByName(
        javax.swing.JComboBox<String> comboBox,
        String name) {

    for (int i = 0; i < comboBox.getItemCount(); i++) {

        String item = comboBox.getItemAt(i);

        if (item != null && item.endsWith(" - " + name)) {
            comboBox.setSelectedIndex(i);
            return;
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppointmentManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentId;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtCreatedBy;
    // End of variables declaration//GEN-END:variables
private void clearFields() {

    txtAppointmentId.setText("");
    txtAppointmentNo.setText("");
    txtAppointmentDate.setText("");
    txtAppointmentTime.setText("");
    txtCreatedBy.setText("");

    cmbPatient.setSelectedIndex(0);
    cmbDentist.setSelectedIndex(0);
    cmbTreatment.setSelectedIndex(0);
    cmbStatus.setSelectedItem("SCHEDULED");

    tblAppointments.clearSelection();

    txtAppointmentNo.requestFocus();
}
}
