/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.BillDAO;
import dao.AppointmentDAO;
import dao.PatientDAO;
import dao.DentistDAO;
import dao.TreatmentDAO;

import model.Bill;
import model.Appointment;
import model.Patient;
import model.Dentist;
import model.Treatment;
import java.sql.Date;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dinuli Disara
 */
public class BillingManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingManagementForm.class.getName());
private final BillDAO billDAO = new BillDAO();
private final AppointmentDAO appointmentDAO = new AppointmentDAO();
private final PatientDAO patientDAO = new PatientDAO();
private final DentistDAO dentistDAO = new DentistDAO();
private final TreatmentDAO treatmentDAO = new TreatmentDAO();
    /**
     * Creates new form BillingManagementForm
     */
    public BillingManagementForm() {
        initComponents();
        
    
    txtBillId.setEditable(false);
    txtPatientName.setEditable(false);
    txtDentistName.setEditable(false);
    txtTreatmentName.setEditable(false);
    txtConsultationFee.setEditable(false);
    txtTreatmentFee.setEditable(false);
    txtTotalAmount.setEditable(false);
    txtBillDate.setEditable(false);

    loadAppointments();
    loadBills();
    }
    private void loadAppointments() {

       cmbAppointment.removeAllItems();

    cmbAppointment.addItem("Select Appointment");

    List<Appointment> appointments =
            appointmentDAO.getAllAppointments();

    for (Appointment appointment : appointments) {

        cmbAppointment.addItem(
                appointment.getAppointmentId()
                + " - "
                + appointment.getAppointmentNo()
        );
    }
}
    private void loadBills() {

    DefaultTableModel tableModel =
            (DefaultTableModel) tblBills.getModel();

    tableModel.setRowCount(0);

    List<Bill> bills = billDAO.getAllBills();

    for (Bill bill : bills) {

        String appointmentNo = "";
        String patientName = "";
        String dentistName = "";
        String treatmentName = "";

        Appointment appointment =
                appointmentDAO.findById(
                        bill.getAppointmentId()
                );

        if (appointment != null) {

            appointmentNo =
                    appointment.getAppointmentNo();

            Patient patient =
                    patientDAO.findById(
                            appointment.getPatientId()
                    );

            if (patient != null) {
                patientName = patient.getName();
            }

            Dentist dentist =
                    dentistDAO.findById(
                            appointment.getDentistId()
                    );

            if (dentist != null) {
                dentistName = dentist.getName();
            }

            Treatment treatment =
                    treatmentDAO.findById(
                            appointment.getTreatmentId()
                    );

            if (treatment != null) {
                treatmentName = treatment.getTreatmentName();
            }
        }

        tableModel.addRow(new Object[]{
            bill.getBillId(),
            appointmentNo,
            patientName,
            dentistName,
            treatmentName,
            bill.getConsultationFee(),
            bill.getTreatmentFee(),
            bill.getTotalAmount(),
            bill.getPaymentStatus(),
            bill.getBillDate()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBillId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbAppointment = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDentistName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTreatmentName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConsultationFee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTreatmentFee = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtBillDate = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Billing management");

        jLabel2.setText("Bill ID");

        txtBillId.setEditable(false);

        jLabel3.setText("Appointment");

        cmbAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAppointment.addActionListener(this::cmbAppointmentActionPerformed);

        jLabel4.setText("Patient");

        txtPatientName.setEditable(false);

        jLabel5.setText("Dentist");

        txtDentistName.setEditable(false);

        jLabel6.setText("Treatment");

        txtTreatmentName.setEditable(false);

        jLabel7.setText("Consultation Fee");

        txtConsultationFee.setEditable(false);

        jLabel8.setText("Treatment Fee");

        txtTreatmentFee.setEditable(false);

        jLabel9.setText("Total Amount");

        txtTotalAmount.setEditable(false);

        jLabel10.setText("Payment Status");

        cmbPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDING", "PAID", "CANCELLED" }));

        jLabel11.setText("Bill Date");

        txtBillDate.setEditable(false);

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnPrint.setText("Print");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Appointment", "Patient", "Dentist", "Treatment", "Consultation Fee", "Treatment Fee", "Total Amount", "Payment Status", "Bill Date"
            }
        ));
        tblBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBills);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBillId)
                                        .addComponent(cmbAppointment, 0, 364, Short.MAX_VALUE)
                                        .addComponent(txtPatientName)
                                        .addComponent(txtDentistName)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTreatmentFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(txtConsultationFee, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTreatmentName, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtBillDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 360, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerate)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(28, 28, 28)
                                .addComponent(btnPrint)
                                .addGap(36, 36, 36)
                                .addComponent(btnClear)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtBillId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTreatmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnPrint)
                    .addComponent(btnClear)
                    .addComponent(btnRefresh)
                    .addComponent(btnBack))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAppointmentActionPerformed
Object selectedItem = cmbAppointment.getSelectedItem();

    // Nothing selected yet
    if (selectedItem == null
            || cmbAppointment.getSelectedIndex() <= 0) {

        txtPatientName.setText("");
        txtDentistName.setText("");
        txtTreatmentName.setText("");
        txtConsultationFee.setText("");
        txtTreatmentFee.setText("");
        txtTotalAmount.setText("");

        return;
    }

    try {

        String selectedAppointment =
                selectedItem.toString();

        int appointmentId =
                Integer.parseInt(
                        selectedAppointment.split(" - ")[0]
                );

        Appointment appointment =
                appointmentDAO.findById(appointmentId);

        if (appointment == null) {
            return;
        }

        Patient patient =
                patientDAO.findById(
                        appointment.getPatientId()
                );

        Dentist dentist =
                dentistDAO.findById(
                        appointment.getDentistId()
                );

        Treatment treatment =
                treatmentDAO.findById(
                        appointment.getTreatmentId()
                );

        // Patient
        if (patient != null) {
            txtPatientName.setText(
                    patient.getName()
            );
        } else {
            txtPatientName.setText("");
        }

        // Dentist
        if (dentist != null) {

            txtDentistName.setText(
                    dentist.getName()
            );

            txtConsultationFee.setText(
                    String.valueOf(
                            dentist.getConsultationFee()
                    )
            );

        } else {

            txtDentistName.setText("");
            txtConsultationFee.setText("");
        }

        // Treatment
        if (treatment != null) {

            txtTreatmentName.setText(
                    treatment.getTreatmentName()
            );

            txtTreatmentFee.setText(
                    String.valueOf(
                            treatment.getTreatmentFee()
                    )
            );

        } else {

            txtTreatmentName.setText("");
            txtTreatmentFee.setText("");
        }

        calculateTotal();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid appointment selection.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_cmbAppointmentActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
if (cmbAppointment.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        String selectedItem =
                cmbAppointment.getSelectedItem().toString();

        int appointmentId =
                Integer.parseInt(
                        selectedItem.split(" - ")[0]
                );

        // Prevent duplicate bills
        Bill existingBill =
                billDAO.findByAppointmentId(appointmentId);

        if (existingBill != null) {

            JOptionPane.showMessageDialog(
                    this,
                    "A bill already exists for this appointment.",
                    "Duplicate Bill",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        double consultationFee =
                Double.parseDouble(
                        txtConsultationFee.getText().trim()
                );

        double treatmentFee =
                Double.parseDouble(
                        txtTreatmentFee.getText().trim()
                );

        double totalAmount =
                consultationFee + treatmentFee;

        Date billDate =
                new Date(System.currentTimeMillis());

        String paymentStatus =
                cmbPaymentStatus.getSelectedItem().toString();

        Bill bill = new Bill(
                0,
                appointmentId,
                consultationFee,
                treatmentFee,
                totalAmount,
                paymentStatus,
                billDate
        );

        boolean result =
                billDAO.insertBill(bill);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill generated successfully."
            );

            loadBills();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to generate bill.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid fee value.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void tblBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillsMouseClicked
  int selectedRow = tblBills.getSelectedRow();

    if (selectedRow < 0) {
        return;
    }

    // Bill ID
    txtBillId.setText(
            tblBills.getValueAt(selectedRow, 0).toString()
    );

    // Appointment
    String appointmentNo =
            tblBills.getValueAt(selectedRow, 1).toString();

    selectAppointmentByNo(
            cmbAppointment,
            appointmentNo
    );

    // Patient
    txtPatientName.setText(
            tblBills.getValueAt(selectedRow, 2).toString()
    );

    // Dentist
    txtDentistName.setText(
            tblBills.getValueAt(selectedRow, 3).toString()
    );

    // Treatment
    txtTreatmentName.setText(
            tblBills.getValueAt(selectedRow, 4).toString()
    );

    // Consultation Fee
    txtConsultationFee.setText(
            tblBills.getValueAt(selectedRow, 5).toString()
    );

    // Treatment Fee
    txtTreatmentFee.setText(
            tblBills.getValueAt(selectedRow, 6).toString()
    );

    // Total Amount
    txtTotalAmount.setText(
            tblBills.getValueAt(selectedRow, 7).toString()
    );

    // Payment Status
    Object paymentStatus =
            tblBills.getValueAt(selectedRow, 8);

    if (paymentStatus != null) {
        cmbPaymentStatus.setSelectedItem(
                paymentStatus.toString()
        );
    }

    // Bill Date
    Object billDate =
            tblBills.getValueAt(selectedRow, 9);

    if (billDate != null) {
        txtBillDate.setText(billDate.toString());
    } else {
        txtBillDate.setText("");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_tblBillsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
if (txtBillId.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a bill first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        int billId =
                Integer.parseInt(txtBillId.getText().trim());

        String appointmentItem =
                cmbAppointment.getSelectedItem().toString();

        if (cmbAppointment.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an appointment.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int appointmentId =
                Integer.parseInt(
                        appointmentItem.split(" - ")[0]
                );

        double consultationFee =
                Double.parseDouble(
                        txtConsultationFee.getText().trim()
                );

        double treatmentFee =
                Double.parseDouble(
                        txtTreatmentFee.getText().trim()
                );

        double totalAmount =
                consultationFee + treatmentFee;

        String paymentStatus =
                cmbPaymentStatus.getSelectedItem().toString();

        Date billDate =
                Date.valueOf(
                        txtBillDate.getText().trim()
                );

        Bill bill = new Bill(
                billId,
                appointmentId,
                consultationFee,
                treatmentFee,
                totalAmount,
                paymentStatus,
                billDate
        );

        boolean result =
                billDAO.updateBill(bill);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill updated successfully."
            );

            loadBills();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update bill.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numeric values.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid bill date.\nUse format: YYYY-MM-DD",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
  if (txtBillId.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a bill first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int billId;

    try {

        billId = Integer.parseInt(
                txtBillId.getText().trim()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid bill ID.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this bill?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean result =
            billDAO.deleteBill(billId);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Bill deleted successfully."
        );

        loadBills();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to delete bill.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
  loadAppointments();
    loadBills();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
ReceptionistDashboard dashboard =
            new ReceptionistDashboard();

    dashboard.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
   if (txtBillId.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a bill first.",
                "Print Bill",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String billText =
            "========================================\n"
            + "         SUNRISE DENTAL CLINIC\n"
            + "              BILL / RECEIPT\n"
            + "========================================\n\n"

            + "Bill ID:            " + txtBillId.getText() + "\n"
            + "Appointment:        "
            + cmbAppointment.getSelectedItem() + "\n"
            + "Patient:            " + txtPatientName.getText() + "\n"
            + "Dentist:            " + txtDentistName.getText() + "\n"
            + "Treatment:          " + txtTreatmentName.getText() + "\n"
            + "Bill Date:          " + txtBillDate.getText() + "\n\n"

            + "----------------------------------------\n"
            + String.format(
                    "Consultation Fee:   Rs. %.2f%n",
                    Double.parseDouble(txtConsultationFee.getText())
            )
            + String.format(
                    "Treatment Fee:      Rs. %.2f%n",
                    Double.parseDouble(txtTreatmentFee.getText())
            )
            + "----------------------------------------\n"
            + String.format(
                    "TOTAL:              Rs. %.2f%n",
                    Double.parseDouble(txtTotalAmount.getText())
            )
            + "----------------------------------------\n\n"

            + "Payment Status:     "
            + cmbPaymentStatus.getSelectedItem() + "\n\n"

            + "          Thank you for visiting!\n"
            + "========================================";

    javax.swing.JTextArea printArea =
            new javax.swing.JTextArea();

    printArea.setText(billText);

    printArea.setFont(
            new java.awt.Font(
                    "Monospaced",
                    java.awt.Font.PLAIN,
                    12
            )
    );

    try {

        boolean complete =
                printArea.print();

        if (complete) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill printed successfully."
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Printing was cancelled.",
                    "Print Bill",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }

    } catch (java.awt.print.PrinterException e) {

        JOptionPane.showMessageDialog(
                this,
                "Unable to print bill.\n"
                + e.getMessage(),
                "Printing Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed
private void selectAppointmentByNo(
        javax.swing.JComboBox<String> comboBox,
        String appointmentNo) {

    for (int i = 0; i < comboBox.getItemCount(); i++) {

        String item = comboBox.getItemAt(i);

        if (item != null &&
                item.endsWith(" - " + appointmentNo)) {

            comboBox.setSelectedIndex(i);
            return;
        }
    }
}
    private void calculateTotal() {

    try {

        double consultationFee =
                Double.parseDouble(
                        txtConsultationFee.getText().trim()
                );

        double treatmentFee =
                Double.parseDouble(
                        txtTreatmentFee.getText().trim()
                );

        double total =
                consultationFee + treatmentFee;

        txtTotalAmount.setText(
                String.format("%.2f", total)
        );

    } catch (NumberFormatException e) {

        txtTotalAmount.setText("0.00");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBills;
    private javax.swing.JTextField txtBillDate;
    private javax.swing.JTextField txtBillId;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtDentistName;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtTreatmentFee;
    private javax.swing.JTextField txtTreatmentName;
    // End of variables declaration//GEN-END:variables
private void clearFields() {

    txtBillId.setText("");

    if (cmbAppointment.getItemCount() > 0) {
        cmbAppointment.setSelectedIndex(0);
    }

    txtPatientName.setText("");
    txtDentistName.setText("");
    txtTreatmentName.setText("");
    txtConsultationFee.setText("");
    txtTreatmentFee.setText("");
    txtTotalAmount.setText("");

    if (cmbPaymentStatus.getItemCount() > 0) {
        cmbPaymentStatus.setSelectedIndex(0);
    }

    txtBillDate.setText("");

    tblBills.clearSelection();
}
}
