/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DentistDAO;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dentist;
/**
 *
 * @author Dinuli Disara
 */
public class DentistManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DentistManagementForm.class.getName());
private final DentistDAO dentistDAO = new DentistDAO();
private void loadDentists() {

    DefaultTableModel model =
            (DefaultTableModel) tblDentists.getModel();

    model.setRowCount(0);

    List<Dentist> dentists = dentistDAO.getAllDentists();

    for (Dentist dentist : dentists) {

        model.addRow(new Object[]{
            dentist.getDentistId(),
            dentist.getUserId(),
            dentist.getName(),
            dentist.getEmail(),
            dentist.getContactNo(),
            dentist.getSpecialization(),
            dentist.getConsultationFee(),
            dentist.getStatus()
        });
    }
}
private void clearFields() {

    txtUserId.setText("");
    /* txtDentistId.setText("");*/
    txtName.setText("");
    txtEmail.setText("");
    txtContactNo.setText("");
    txtSpecialization.setText("");
    txtConsultationFee.setText("");

    cmbStatus.setSelectedItem("ACTIVE");

    tblDentists.clearSelection();
}
    /**
     *
     * Creates new form DentistManagementForm
     */
    public DentistManagementForm() {
        initComponents();
        loadDentists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        lblConsultationFee = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDentists = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DENTIST MANAGEMENT");

        lblUserId.setText("User ID: ");

        lblName.setText(" Name:");

        lblEmail.setText(" Email: ");

        lblContactNo.setText("Contact No:");

        lblSpecialization.setText(" Specialization:");

        lblConsultationFee.setText(" Consultation Fee: ");

        lblStatus.setText(" Status:  ");

        txtSpecialization.addActionListener(this::txtSpecializationActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        cmbStatus.addActionListener(this::cmbStatusActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDeactivate.setText("Deactivate");
        btnDeactivate.addActionListener(this::btnDeactivateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblDentists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                " ID ", "User ID", "Name", "Email", "Contact No", "Specialization", "Consultation Fee", "Status"
            }
        ));
        tblDentists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDentistsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDentists);
        if (tblDentists.getColumnModel().getColumnCount() > 0) {
            tblDentists.getColumnModel().getColumn(2).setResizable(false);
            tblDentists.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserId)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblContactNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                    .addComponent(lblSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblConsultationFee)
                                            .addComponent(lblStatus))
                                        .addGap(78, 78, 78)))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtEmail)
                                    .addComponent(txtUserId)
                                    .addComponent(txtContactNo)
                                    .addComponent(txtSpecialization)
                                    .addComponent(txtConsultationFee)
                                    .addComponent(cmbStatus, 0, 373, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnDeactivate)
                                .addGap(76, 76, 76)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserId)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultationFee)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeactivate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
 String userIdText = txtUserId.getText().trim();
    String name = txtName.getText().trim();
    String email = txtEmail.getText().trim();
    String contactNo = txtContactNo.getText().trim();
    String specialization = txtSpecialization.getText().trim();
    String feeText = txtConsultationFee.getText().trim();

    // Validation
    if (userIdText.isEmpty() ||
        name.isEmpty() ||
        email.isEmpty() ||
        contactNo.isEmpty() ||
        specialization.isEmpty() ||
        feeText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int userId;
    double consultationFee;

    try {
        userId = Integer.parseInt(userIdText);
        consultationFee = Double.parseDouble(feeText);
    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "User ID must be a number and consultation fee must be a valid number.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    String status = cmbStatus.getSelectedItem().toString();

    Dentist dentist = new Dentist();

    dentist.setUserId(userId);
    dentist.setName(name);
    dentist.setEmail(email);
    dentist.setContactNo(contactNo);
    dentist.setSpecialization(specialization);
    dentist.setConsultationFee(consultationFee);
    dentist.setStatus(status);

    boolean success = dentistDAO.insertDentist(dentist);

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist added successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

        loadDentists();
        clearForm();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to add dentist.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 if (txtUserId.getText().trim().isEmpty()
            || txtUserId.getText().trim().isEmpty()
            || txtName.getText().trim().isEmpty()
            || txtEmail.getText().trim().isEmpty()
            || txtContactNo.getText().trim().isEmpty()
            || txtSpecialization.getText().trim().isEmpty()
            || txtConsultationFee.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill in all fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // 2. YOUR EXISTING UPDATE CODE
    try {

        int dentistId = Integer.parseInt(txtUserId.getText().trim());
        int userId = Integer.parseInt(txtUserId.getText().trim());

        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String contactNo = txtContactNo.getText().trim();
        String specialization = txtSpecialization.getText().trim();

        double consultationFee =
                Double.parseDouble(txtConsultationFee.getText().trim());

        String status =
                cmbStatus.getSelectedItem().toString();

        Dentist dentist = new Dentist();

        dentist.setDentistId(dentistId);
        dentist.setUserId(userId);
        dentist.setName(name);
        dentist.setEmail(email);
        dentist.setContactNo(contactNo);
        dentist.setSpecialization(specialization);
        dentist.setConsultationFee(consultationFee);
        dentist.setStatus(status);

        DentistDAO dentistDAO = new DentistDAO();

        boolean success = dentistDAO.updateDentist(dentist);

        if (success) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist updated successfully."
            );

            loadDentistTable();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update dentist.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numbers for Dentist ID, User ID and Consultation Fee.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
try {

        int dentistId = Integer.parseInt(
                txtUserId.getText().trim()
        );

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to deactivate this dentist?",
                "Confirm Deactivation",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            boolean success = dentistDAO.deactivateDentist(dentistId);

            if (success) {

                JOptionPane.showMessageDialog(
                        this,
                        "Dentist deactivated successfully."
                );

                loadDentists();
                clearForm();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Failed to deactivate dentist.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a dentist first.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }     // TODO add your handling code here:
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void txtSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializationActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblDentistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDentistsMouseClicked
int selectedRow = tblDentists.getSelectedRow();

    if (selectedRow >= 0) {

        /*txtDentistId.setText(
        tblDentists.getValueAt(selectedRow, 0).toString()
        );*/

        txtUserId.setText(
                tblDentists.getValueAt(selectedRow, 1).toString()
        );

        txtName.setText(
                tblDentists.getValueAt(selectedRow, 2).toString()
        );

        txtEmail.setText(
                tblDentists.getValueAt(selectedRow, 3).toString()
        );

        txtContactNo.setText(
                tblDentists.getValueAt(selectedRow, 4).toString()
        );

        txtSpecialization.setText(
                tblDentists.getValueAt(selectedRow, 5).toString()
        );

        txtConsultationFee.setText(
                tblDentists.getValueAt(selectedRow, 6).toString()
        );

        cmbStatus.setSelectedItem(
                tblDentists.getValueAt(selectedRow, 7).toString()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblDentistsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DentistManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultationFee;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTable tblDentists;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void loadDentistTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
