/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.mycompany.sunrisedentalclinic.model.User;
import dao.DentistDAO;
import model.Dentist;
import dao.MedicalRecordDAO;
import dao.PatientDAO;
import dao.AppointmentDAO;

import model.MedicalRecord;
import model.Dentist;
import model.Patient;
import model.Appointment;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Date;


/**
 *
 * @author Dinuli Disara
 */
public class MedicalRecordManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicalRecordManagementForm.class.getName());

private final MedicalRecordDAO medicalRecordDAO = new MedicalRecordDAO();
private final DentistDAO dentistDAO = new DentistDAO();
private final PatientDAO patientDAO = new PatientDAO();
private final AppointmentDAO appointmentDAO = new AppointmentDAO();

private User loggedInUser;
private Dentist loggedInDentist;
    /**
     * Creates new form MedicalRecordManagementForm
     */
    public MedicalRecordManagementForm(User user) {

    initComponents();

    this.loggedInUser = user;

    txtRecordId.setEditable(false);

    loadLoggedInDentist();
    loadPatients();
    loadAppointments();
    loadMedicalRecords();
}
    private void loadLoggedInDentist() {

    if (loggedInUser == null) {

        JOptionPane.showMessageDialog(
                this,
                "Logged-in user information is missing.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    loggedInDentist =
            dentistDAO.findByUserId(
                    loggedInUser.getUserId()
            );

    if (loggedInDentist == null) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist profile not found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    private void loadPatients() {

    cmbPatient.removeAllItems();
    cmbPatient.addItem("Select Patient");

    List<Patient> patients =
            patientDAO.getAllPatients();

    for (Patient patient : patients) {

        cmbPatient.addItem(
                patient.getPatientId()
                + " - "
                + patient.getName()
        );
    }
}
    private void loadAppointments() {

    cmbAppointment.removeAllItems();
    cmbAppointment.addItem("Select Appointment");

    if (loggedInDentist == null) {
        return;
    }

    List<Appointment> appointments =
            appointmentDAO.getAppointmentsByDentistId(
                    loggedInDentist.getDentistId()
            );

    for (Appointment appointment : appointments) {

        cmbAppointment.addItem(
                appointment.getAppointmentId()
                + " - "
                + appointment.getAppointmentNo()
        );
    }
}
    private void loadMedicalRecords() {

    DefaultTableModel tableModel =
            (DefaultTableModel) tblMedicalRecords.getModel();

    tableModel.setRowCount(0);

    if (loggedInDentist == null) {
        return;
    }

    List<MedicalRecord> records =
            medicalRecordDAO.getRecordsByDentistId(
                    loggedInDentist.getDentistId()
            );

    for (MedicalRecord record : records) {

        String patientName = "";
        String appointmentNo = "";

        Patient patient =
                patientDAO.findById(
                        record.getPatientId()
                );

        if (patient != null) {
            patientName = patient.getName();
        }

        Appointment appointment =
                appointmentDAO.findById(
                        record.getAppointmentId()
                );

        if (appointment != null) {
            appointmentNo =
                    appointment.getAppointmentNo();
        }

        tableModel.addRow(new Object[]{
            record.getRecordId(),
            patientName,
            appointmentNo,
            record.getDiagnosis(),
            record.getTreatmentNotes(),
            record.getPrescription(),
            record.getRecordDate()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRecordId = new javax.swing.JTextField();
        cmbPatient = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbAppointment = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTreatmentNotes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrescription = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtRecordDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedicalRecords = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MEDICAL RECORDS");

        jLabel2.setText("Record ID");

        txtRecordId.setEditable(false);

        cmbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Patient");

        jLabel4.setText("Appointment");

        cmbAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Diagnosis");

        jLabel6.setText("Treatment Notes");

        txtTreatmentNotes.setColumns(20);
        txtTreatmentNotes.setRows(5);
        jScrollPane1.setViewportView(txtTreatmentNotes);

        jLabel7.setText("Prescription");

        txtPrescription.setColumns(20);
        txtPrescription.setRows(5);
        jScrollPane2.setViewportView(txtPrescription);

        jLabel8.setText("Record Date");

        txtRecordDate.addActionListener(this::txtRecordDateActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblMedicalRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Patient", "Appointment", "Diagnosis", "Treatment Notes", "Prescription", "Record Date"
            }
        ));
        tblMedicalRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicalRecordsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMedicalRecords);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiagnosis)
                            .addComponent(cmbAppointment, 0, 191, Short.MAX_VALUE)
                            .addComponent(cmbPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRecordId))
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnRefresh)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRecordDate)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(40, 40, 40))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnAdd)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(66, 66, 66)
                        .addComponent(btnClear)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRecordId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRecordDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecordDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordDateActionPerformed

    private void tblMedicalRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicalRecordsMouseClicked
 int selectedRow = tblMedicalRecords.getSelectedRow();

    if (selectedRow < 0) {
        return;
    }

    // Record ID
    txtRecordId.setText(
            tblMedicalRecords.getValueAt(selectedRow, 0).toString()
    );

    // Patient
    String patientName =
            tblMedicalRecords.getValueAt(selectedRow, 1).toString();

    selectComboByName(cmbPatient, patientName);

    // Appointment
    String appointmentNo =
            tblMedicalRecords.getValueAt(selectedRow, 2).toString();

    selectAppointmentByNo(cmbAppointment, appointmentNo);

    // Diagnosis
    txtDiagnosis.setText(
            tblMedicalRecords.getValueAt(selectedRow, 3).toString()
    );

    // Treatment Notes
    txtTreatmentNotes.setText(
            tblMedicalRecords.getValueAt(selectedRow, 4).toString()
    );

    // Prescription
    txtPrescription.setText(
            tblMedicalRecords.getValueAt(selectedRow, 5).toString()
    );

    // Record Date
    Object recordDate =
            tblMedicalRecords.getValueAt(selectedRow, 6);

    txtRecordDate.setText(
            recordDate != null ? recordDate.toString() : ""
    );        // TODO add your handling code here:
    }//GEN-LAST:event_tblMedicalRecordsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
// Make sure a dentist is logged in
    if (loggedInDentist == null) {
        JOptionPane.showMessageDialog(
                this,
                "Dentist information is not available.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Check selections
    if (cmbPatient.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a patient.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (cmbAppointment.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String diagnosis = txtDiagnosis.getText().trim();
    String treatmentNotes = txtTreatmentNotes.getText().trim();
    String prescription = txtPrescription.getText().trim();
    String recordDateText = txtRecordDate.getText().trim();

    if (diagnosis.isEmpty() || treatmentNotes.isEmpty()
            || recordDateText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill Diagnosis, Treatment Notes and Record Date.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {

        // Get patient ID from Patient combo
        String patientItem =
                cmbPatient.getSelectedItem().toString();

        int patientId =
                Integer.parseInt(
                        patientItem.split(" - ")[0]
                );

        // Get appointment ID from Appointment combo
        String appointmentItem =
                cmbAppointment.getSelectedItem().toString();

        int appointmentId =
                Integer.parseInt(
                        appointmentItem.split(" - ")[0]
                );

        // Record date
        Date recordDate =
                Date.valueOf(recordDateText);

        // Create medical record using logged-in dentist
        MedicalRecord record = new MedicalRecord(
                0,
                patientId,
                loggedInDentist.getDentistId(),
                appointmentId,
                diagnosis,
                treatmentNotes,
                prescription,
                recordDate
        );

        boolean result =
                medicalRecordDAO.insertMedicalRecord(record);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Medical record added successfully."
            );

            loadMedicalRecords();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to add medical record.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid patient or appointment ID.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid record date.\n\n"
                + "Use format: YYYY-MM-DD\n"
                + "Example: 2026-09-04",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 if (txtRecordId.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a medical record first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (loggedInDentist == null) {

        JOptionPane.showMessageDialog(
                this,
                "Dentist information is not available.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }
    if (!validatePatientAppointment()) {
    return;
}

    if (cmbPatient.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a patient.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (cmbAppointment.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String diagnosis = txtDiagnosis.getText().trim();
    String treatmentNotes = txtTreatmentNotes.getText().trim();
    String prescription = txtPrescription.getText().trim();
    String recordDateText = txtRecordDate.getText().trim();

    if (diagnosis.isEmpty()
            || treatmentNotes.isEmpty()
            || recordDateText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please fill Diagnosis, Treatment Notes and Record Date.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        int recordId =
                Integer.parseInt(txtRecordId.getText().trim());

        String patientItem =
                cmbPatient.getSelectedItem().toString();

        int patientId =
                Integer.parseInt(
                        patientItem.split(" - ")[0]
                );

        String appointmentItem =
                cmbAppointment.getSelectedItem().toString();

        int appointmentId =
                Integer.parseInt(
                        appointmentItem.split(" - ")[0]
                );

        Date recordDate =
                Date.valueOf(recordDateText);

        /*
         * IMPORTANT:
         * Dentist ID comes from the logged-in dentist.
         */
        int dentistId =
                loggedInDentist.getDentistId();

        MedicalRecord record = new MedicalRecord(
                recordId,
                patientId,
                dentistId,
                appointmentId,
                diagnosis,
                treatmentNotes,
                prescription,
                recordDate
        );

        boolean result =
                medicalRecordDAO.updateMedicalRecord(record);

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Medical record updated successfully."
            );

            loadMedicalRecords();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update medical record.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid record, patient or appointment ID.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid record date.\n\n"
                + "Use format: YYYY-MM-DD\n"
                + "Example: 2026-09-04",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
 if (txtRecordId.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a medical record first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int recordId;

    try {

        recordId = Integer.parseInt(
                txtRecordId.getText().trim()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid medical record ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this medical record?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean result =
            medicalRecordDAO.deleteMedicalRecord(recordId);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Medical record deleted successfully."
        );

        loadMedicalRecords();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to delete medical record.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
loadPatients();
    loadAppointments();
    loadMedicalRecords();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    DentistDashboard dashboard =
            new DentistDashboard(loggedInUser);

    dashboard.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed
private void selectComboByName(
        javax.swing.JComboBox<String> comboBox,
        String name) {

    for (int i = 0; i < comboBox.getItemCount(); i++) {

        String item = comboBox.getItemAt(i);

        if (item != null && item.endsWith(" - " + name)) {
            comboBox.setSelectedIndex(i);
            return;
        }
    }
}
    private void selectAppointmentByNo(
        javax.swing.JComboBox<String> comboBox,
        String appointmentNo) {

    for (int i = 0; i < comboBox.getItemCount(); i++) {

        String item = comboBox.getItemAt(i);

        if (item != null && item.endsWith(" - " + appointmentNo)) {
            comboBox.setSelectedIndex(i);
            return;
        }
    }
}

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
        () -> new MedicalRecordManagementForm(null).setVisible(true)
);
    }
private boolean validatePatientAppointment() {

    if (cmbPatient.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a patient.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return false;
    }

    if (cmbAppointment.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return false;
    }

    try {

        String patientItem =
                cmbPatient.getSelectedItem().toString();

        int selectedPatientId =
                Integer.parseInt(
                        patientItem.split(" - ")[0]
                );

        String appointmentItem =
                cmbAppointment.getSelectedItem().toString();

        int selectedAppointmentId =
                Integer.parseInt(
                        appointmentItem.split(" - ")[0]
                );

        Appointment appointment =
                appointmentDAO.findById(
                        selectedAppointmentId
                );

        if (appointment == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selected appointment was not found.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return false;
        }

        if (appointment.getPatientId() != selectedPatientId) {

            JOptionPane.showMessageDialog(
                    this,
                    "The selected patient does not belong to "
                    + "the selected appointment.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return false;
        }

        // Also make sure appointment belongs to logged-in dentist
        if (loggedInDentist != null
                && appointment.getDentistId()
                != loggedInDentist.getDentistId()) {

            JOptionPane.showMessageDialog(
                    this,
                    "You can only create records for "
                    + "your own appointments.",
                    "Access Denied",
                    JOptionPane.ERROR_MESSAGE
            );

            return false;
        }

        return true;

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid patient or appointment selection.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return false;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMedicalRecords;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextArea txtPrescription;
    private javax.swing.JTextField txtRecordDate;
    private javax.swing.JTextField txtRecordId;
    private javax.swing.JTextArea txtTreatmentNotes;
    // End of variables declaration//GEN-END:variables

private void clearFields() {

    txtRecordId.setText("");

    if (cmbPatient.getItemCount() > 0) {
        cmbPatient.setSelectedIndex(0);
    }

    if (cmbAppointment.getItemCount() > 0) {
        cmbAppointment.setSelectedIndex(0);
    }

    txtDiagnosis.setText("");
    txtTreatmentNotes.setText("");
    txtPrescription.setText("");
    txtRecordDate.setText("");

    tblMedicalRecords.clearSelection();

    txtDiagnosis.requestFocus();
}
}
