/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.PatientDAO;
import model.Patient;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dinuli Disara
 */
public class PatientManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientManagementForm.class.getName());
private final PatientDAO patientDAO = new PatientDAO();
    /**
     * Creates new form PatientManagementForm
     */
    public PatientManagementForm() {
        initComponents();
        txtPatientId.setEditable(false);
    loadPatients();
    }
private void loadPatients() {

    DefaultTableModel model =
            (DefaultTableModel) tblPatients.getModel();

    model.setRowCount(0);

    List<Patient> patients = patientDAO.getAllPatients();

    for (Patient patient : patients) {

        model.addRow(new Object[]{
            patient.getPatientId(),
            patient.getName(),
            patient.getAddress(),
            patient.getContactNo(),
            patient.getDateOfBirth(),
            patient.getGender()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Patient Management ");

        jLabel2.setText("Patient ID");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("Contact No");

        jLabel6.setText("Date of Birth ");

        jLabel7.setText("Gender");

        txtPatientId.setEditable(false);

        txtDateOfBirth.setText("YYYY-MM-DD");
        txtDateOfBirth.setToolTipText("");
        txtDateOfBirth.addActionListener(this::txtDateOfBirthActionPerformed);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Address", "Contact No", "Date of Birth", "Gender"
            }
        ));
        tblPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatients);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(50, 50, 50)
                                .addComponent(btnUpdate)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientId)
                            .addComponent(txtName)
                            .addComponent(txtAddress)
                            .addComponent(txtContactNo)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthActionPerformed

    private void tblPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientsMouseClicked
 int selectedRow = tblPatients.getSelectedRow();

    if (selectedRow >= 0) {

        txtPatientId.setText(
                tblPatients.getValueAt(selectedRow, 0).toString()
        );

        txtName.setText(
                tblPatients.getValueAt(selectedRow, 1).toString()
        );

        txtAddress.setText(
                tblPatients.getValueAt(selectedRow, 2).toString()
        );

        txtContactNo.setText(
                tblPatients.getValueAt(selectedRow, 3).toString()
        );

        Object dob = tblPatients.getValueAt(selectedRow, 4);

        if (dob != null) {
            txtDateOfBirth.setText(dob.toString());
        } else {
            txtDateOfBirth.setText("");
        }

        Object gender = tblPatients.getValueAt(selectedRow, 5);

        if (gender != null) {
            cmbGender.setSelectedItem(gender.toString());
        } else {
            cmbGender.setSelectedIndex(0);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
String name = txtName.getText().trim();
    String address = txtAddress.getText().trim();
    String contactNo = txtContactNo.getText().trim();
    String dateOfBirthText = txtDateOfBirth.getText().trim();
    String gender = cmbGender.getSelectedItem().toString();

    // Required field validation
    if (name.isEmpty() || address.isEmpty() || contactNo.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please fill in Name, Address and Contact No.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Date validation
    Date dateOfBirth;

    if (dateOfBirthText.isEmpty()) {
        dateOfBirth = null;
    } else {
        try {
            dateOfBirth = Date.valueOf(dateOfBirthText);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid date. Please use YYYY-MM-DD format.\nExample: 2000-05-15",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    }

    Patient patient = new Patient(
            0,
            name,
            address,
            contactNo,
            dateOfBirth,
            gender
    );

    boolean result = patientDAO.insertPatient(patient);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Patient added successfully."
        );

        loadPatients();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to add patient.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 if (txtPatientId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a patient first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String name = txtName.getText().trim();
    String address = txtAddress.getText().trim();
    String contactNo = txtContactNo.getText().trim();
    String dateOfBirthText = txtDateOfBirth.getText().trim();
    String gender = cmbGender.getSelectedItem().toString();

    if (name.isEmpty() || address.isEmpty() || contactNo.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please fill in Name, Address and Contact No.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int patientId;
    Date dateOfBirth;

    try {
        patientId = Integer.parseInt(txtPatientId.getText().trim());

        if (dateOfBirthText.isEmpty()) {
            dateOfBirth = null;
        } else {
            dateOfBirth = Date.valueOf(dateOfBirthText);
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid patient ID.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid date. Please use YYYY-MM-DD format.\nExample: 2000-05-15",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    Patient patient = new Patient(
            patientId,
            name,
            address,
            contactNo,
            dateOfBirth,
            gender
    );

    boolean result = patientDAO.updatePatient(patient);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Patient updated successfully."
        );

        loadPatients();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to update patient.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    if (txtPatientId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a patient first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int patientId;

    try {
        patientId = Integer.parseInt(txtPatientId.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "Invalid patient ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this patient?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean result = patientDAO.deletePatient(patientId);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Patient deleted successfully."
        );

        loadPatients();
        clearFields();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to delete patient.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables
private void clearFields() {

    txtPatientId.setText("");
    txtName.setText("");
    txtAddress.setText("");
    txtContactNo.setText("");
    txtDateOfBirth.setText("");

    cmbGender.setSelectedIndex(0);

    tblPatients.clearSelection();

    txtName.requestFocus();
}
}
