/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Dinuli Disara
 */
public class ReceptionistDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceptionistDashboard.class.getName());

    /**
     * Creates new form ReceptionistDashboard
     */
    public ReceptionistDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewPatients = new javax.swing.JButton();
        btnManageAppointments = new javax.swing.JButton();
        btnManageBilling = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - Receptionist Dashboard");

        jLabel1.setText("Welcome, Receptionist");

        jLabel2.setText("RECEPTIONIST DASHBOARD");

        btnViewPatients.setText("Patient Management");
        btnViewPatients.addActionListener(this::btnViewPatientsActionPerformed);

        btnManageAppointments.setText("Appointment Management");
        btnManageAppointments.addActionListener(this::btnManageAppointmentsActionPerformed);

        btnManageBilling.setText("Billing Management");
        btnManageBilling.addActionListener(this::btnManageBillingActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageAppointments)
                            .addComponent(btnViewPatients)
                            .addComponent(btnManageBilling)
                            .addComponent(btnLogout))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnViewPatients)
                .addGap(18, 18, 18)
                .addComponent(btnManageAppointments)
                .addGap(18, 18, 18)
                .addComponent(btnManageBilling)
                .addGap(26, 26, 26)
                .addComponent(btnLogout)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
 PatientManagementForm patientForm = new PatientManagementForm();
    patientForm.setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
 LoginForm loginForm = new LoginForm();
    loginForm.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAppointmentsActionPerformed
 AppointmentManagementForm appointmentForm =
            new AppointmentManagementForm();

    appointmentForm.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageAppointmentsActionPerformed

    private void btnManageBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBillingActionPerformed
     try {

        BillingManagementForm billingForm =
                new BillingManagementForm();

        billingForm.setLocationRelativeTo(this);
        billingForm.setVisible(true);

    } catch (Exception e) {

        e.printStackTrace();

        JOptionPane.showMessageDialog(
                this,
                "Billing form could not open.\n\n"
                + e.getClass().getSimpleName()
                + "\n"
                + e.getMessage(),
                "Billing Form Error",
                JOptionPane.ERROR_MESSAGE
        );
    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnManageBillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReceptionistDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAppointments;
    private javax.swing.JButton btnManageBilling;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
