/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.TreatmentDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Treatment;
/**
 *
 * @author Dinuli Disara
 */
public class TreatmentManagementForm extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TreatmentManagementForm.class.getName());
private final TreatmentDAO treatmentDAO = new TreatmentDAO();
    /**
     * Creates new form TreatmentManagementForm
     */
    public TreatmentManagementForm() {
        initComponents();
        loadTreatments();
    }
private void loadTreatments() {

    DefaultTableModel model =
            (DefaultTableModel) tblTreatments.getModel();

    model.setRowCount(0);

    List<Treatment> treatments =
            treatmentDAO.getAllTreatments();

    for (Treatment treatment : treatments) {

        model.addRow(new Object[]{
            treatment.getTreatmentId(),
            treatment.getTreatmentName(),
            treatment.getDescription(),
            treatment.getTreatmentFee(),
            treatment.getStatus()
        });
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTreatmentId = new javax.swing.JTextField();
        txtTreatmentName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtTreatmentFee = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreatments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TREATMENT MANAGEMENT");

        jLabel2.setText("Treatment ID:");

        jLabel3.setText("Treatment Name: ");

        jLabel4.setText("Description:");

        jLabel5.setText("Treatment Fee:");

        jLabel6.setText("Status: ");

        txtTreatmentId.setEditable(false);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDeactivate.setText("Deactivate");
        btnDeactivate.addActionListener(this::btnDeactivateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblTreatments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Treatment ID", "Treatment Name", "Description", "Treatment Fee", "Status"
            }
        ));
        tblTreatments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreatmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTreatments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnDeactivate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 41, Short.MAX_VALUE)))))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTreatmentId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTreatmentName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 265, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTreatmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTreatmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDeactivate)
                    .addComponent(btnClear))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTreatmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTreatmentsMouseClicked
  int selectedRow = tblTreatments.getSelectedRow();

    if (selectedRow >= 0) {
        txtTreatmentId.setText(
            tblTreatments.getValueAt(selectedRow, 0).toString()
        );

        txtTreatmentName.setText(
            tblTreatments.getValueAt(selectedRow, 1).toString()
        );

        txtDescription.setText(
            tblTreatments.getValueAt(selectedRow, 2).toString()
        );

        txtTreatmentFee.setText(
            tblTreatments.getValueAt(selectedRow, 3).toString()
        );

        cmbStatus.setSelectedItem(
            tblTreatments.getValueAt(selectedRow, 4).toString()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblTreatmentsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    String name = txtTreatmentName.getText().trim();
    String description = txtDescription.getText().trim();
    String feeText = txtTreatmentFee.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();

    if (name.isEmpty() || description.isEmpty() || feeText.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please fill all fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    double fee;

    try {
        fee = Double.parseDouble(feeText);

        if (fee < 0) {
            JOptionPane.showMessageDialog(this,
                    "Treatment fee cannot be negative.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Please enter a valid treatment fee.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    Treatment treatment = new Treatment(
            0,
            name,
            description,
            fee,
            status
    );

    boolean result = treatmentDAO.insertTreatment(treatment);

    if (result) {
        JOptionPane.showMessageDialog(this,
                "Treatment added successfully.");

        loadTreatments();
        clearFields();

    } else {
        JOptionPane.showMessageDialog(this,
                "Failed to add treatment.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
   if (txtTreatmentId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please select a treatment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    String name = txtTreatmentName.getText().trim();
    String description = txtDescription.getText().trim();
    String feeText = txtTreatmentFee.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();

    if (name.isEmpty() || description.isEmpty() || feeText.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please fill all fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int treatmentId;
    double fee;

    try {
        treatmentId = Integer.parseInt(txtTreatmentId.getText().trim());
        fee = Double.parseDouble(feeText);

        if (fee < 0) {
            JOptionPane.showMessageDialog(this,
                    "Treatment fee cannot be negative.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Please enter valid treatment details.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    Treatment treatment = new Treatment(
            treatmentId,
            name,
            description,
            fee,
            status
    );

    boolean result = treatmentDAO.updateTreatment(treatment);

    if (result) {
        JOptionPane.showMessageDialog(this,
                "Treatment updated successfully.");

        loadTreatments();
        clearFields();

    } else {
        JOptionPane.showMessageDialog(this,
                "Failed to update treatment.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
 if (txtTreatmentId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please select a treatment first.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int treatmentId;

    try {
        treatmentId = Integer.parseInt(txtTreatmentId.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Invalid treatment ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to deactivate this treatment?",
            "Confirm Deactivation",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean result = treatmentDAO.deactivateTreatment(treatmentId);

    if (result) {
        JOptionPane.showMessageDialog(this,
                "Treatment deactivated successfully.");

        loadTreatments();
        clearFields();

    } else {
        JOptionPane.showMessageDialog(this,
                "Failed to deactivate treatment.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TreatmentManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTreatments;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtTreatmentFee;
    private javax.swing.JTextField txtTreatmentId;
    private javax.swing.JTextField txtTreatmentName;
    // End of variables declaration//GEN-END:variables
private void clearFields() {
    txtTreatmentId.setText("");
    txtTreatmentName.setText("");
    txtDescription.setText("");
    txtTreatmentFee.setText("");
    cmbStatus.setSelectedItem("ACTIVE");
    tblTreatments.clearSelection();
    txtTreatmentName.requestFocus();
}
}
