/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.mycompany.sunrisedentalclinic.dao.UserDAO;
import com.mycompany.sunrisedentalclinic.model.User;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UserManagementForm extends javax.swing.JFrame {

    private final UserDAO userDAO = new UserDAO();

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(
                    UserManagementForm.class.getName()
            );

    public UserManagementForm() {

        initComponents();

        setLocationRelativeTo(null);

        loadUsers();
    }

    private void loadUsers() {

        DefaultTableModel model =
                (DefaultTableModel) tblUsers.getModel();

        model.setRowCount(0);

        List<User> users = userDAO.getAllUsers();

        for (User user : users) {

            model.addRow(new Object[]{
                user.getUserId(),
                user.getUsername(),
                user.getRole(),
                user.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USER MANAGEMENT");

        jLabel2.setText("Username");

        jLabel3.setText("Role");

        jLabel4.setText("Status");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "DENTIST", "RECEPTIONIST" }));
        cmbRole.addActionListener(this::cmbRoleActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDeactivate.setText("Deactivate");
        btnDeactivate.addActionListener(this::btnDeactivateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Role ", "Status"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsers);

        jLabel5.setText("Password");

        txtPassword.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(249, 249, 249))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeactivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDeactivate)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
 int selectedRow = tblUsers.getSelectedRow();

    if (selectedRow == -1) {
        return;
    }

    String username =
            tblUsers.getValueAt(selectedRow, 1).toString();

    String role =
            tblUsers.getValueAt(selectedRow, 2).toString();

    String status =
            tblUsers.getValueAt(selectedRow, 3).toString();

    txtUsername.setText(username);

    cmbRole.setSelectedItem(role);

    cmbStatus.setSelectedItem(status);        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
  

    String username = txtUsername.getText().trim();

    String password =
            new String(txtPassword.getPassword());

    String role =
            cmbRole.getSelectedItem().toString();

    String status =
            cmbStatus.getSelectedItem().toString();

    if (username.isEmpty() || password.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Username and password are required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (userDAO.findByUsername(username) != null) {

        JOptionPane.showMessageDialog(
                this,
                "Username already exists.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    User user = new User(
            username,
            password,
            role,
            status
    );

    boolean success = userDAO.insertUser(user);

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "User added successfully."
        );

        loadUsers();
        clearForm();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to add user.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 int selectedRow = tblUsers.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a user to update.",
                "Update User",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int userId = Integer.parseInt(
            tblUsers.getValueAt(selectedRow, 0).toString()
    );

    String username = txtUsername.getText().trim();

    String password =
            new String(txtPassword.getPassword());

    String role =
            cmbRole.getSelectedItem().toString();

    String status =
            cmbStatus.getSelectedItem().toString();

    // Validate username
    if (username.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Username is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Get existing user
    User existingUser = userDAO.findById(userId);

    if (existingUser == null) {

        JOptionPane.showMessageDialog(
                this,
                "User not found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Check whether username belongs to another user
    User userWithSameUsername =
            userDAO.findByUsername(username);

    if (userWithSameUsername != null
            && userWithSameUsername.getUserId() != userId) {

        JOptionPane.showMessageDialog(
                this,
                "Username already exists.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // If password field is empty,
    // keep the existing password
    String passwordHash;

    if (password.isEmpty()) {
        passwordHash = existingUser.getPasswordHash();
    } else {
        passwordHash = password;
    }

    User updatedUser = new User(
            userId,
            username,
            passwordHash,
            role,
            status,
            existingUser.getCreatedAt()
    );

    boolean success = userDAO.updateUser(updatedUser);

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "User updated successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

        loadUsers();
        clearForm();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to update user.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
  int selectedRow = tblUsers.getSelectedRow();

    if (selectedRow == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a user to deactivate.",
                "Deactivate User",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int userId = Integer.parseInt(
            tblUsers.getValueAt(selectedRow, 0).toString()
    );

    String username =
            tblUsers.getValueAt(selectedRow, 1).toString();

    String currentStatus =
            tblUsers.getValueAt(selectedRow, 3).toString();

    // Check whether already inactive
    if ("INACTIVE".equalsIgnoreCase(currentStatus)) {

        JOptionPane.showMessageDialog(
                this,
                "This user is already inactive.",
                "Deactivate User",
                JOptionPane.INFORMATION_MESSAGE
        );

        return;
    }

    // Confirmation
    int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to deactivate user: "
                    + username + "?",
            "Confirm Deactivation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirmation != JOptionPane.YES_OPTION) {
        return;
    }

    // Deactivate user
    boolean success = userDAO.deactivateUser(userId);

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "User deactivated successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

        loadUsers();
        clearForm();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to deactivate user.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeactivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblUsers;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  
    txtUsername.setText("");

    cmbRole.setSelectedIndex(0);

    cmbStatus.setSelectedIndex(0);

    tblUsers.clearSelection();

    txtUsername.requestFocus();

    
    }
}
